"""Scheduled upstream merges and changelog pull requests."""

from __future__ import annotations

import asyncio
import logging
import re
from datetime import UTC, datetime

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

from app.changelog import grouped_commits, included_commits, prepend, render_section
from app.github_client import GitHubError
from app.interfaces import Deps
from app.models import FORK_REPO, LABEL_NEEDS_HUMAN, UPSTREAM_REPO
from app.request_security import is_allowed_local_request

logger = logging.getLogger(__name__)
_REQUIREMENTS_FILE = re.compile(r"^requirements/[^/]+\.txt$")


def _record(
    deps: Deps,
    started_at: float,
    outcome: str,
    *,
    before_sha: str | None = None,
    after_sha: str | None = None,
    detail: str | None = None,
    pr_url: str | None = None,
    issue_number: int | None = None,
) -> None:
    deps.db.record_upstream_sync(
        started_at,
        outcome,
        before_sha=before_sha,
        after_sha=after_sha,
        detail=detail,
        pr_url=pr_url,
        issue_number=issue_number,
    )


async def _record_conflict(
    deps: Deps,
    started_at: float,
    before_sha: str,
) -> dict:
    branch = deps.settings.upstream_sync_branch
    stored_number = deps.db.get_meta("conflict_issue_number")
    existing_number = int(stored_number) if stored_number and stored_number.isdecimal() else None
    if existing_number is not None:
        try:
            issue = await deps.github.get_issue(existing_number)
        except GitHubError as error:
            if error.status_code != 404:
                raise
            issue = None
        if issue is not None and issue.state == "open":
            detail = f"existing issue #{existing_number}"
            _record(
                deps,
                started_at,
                "conflict",
                before_sha=before_sha,
                detail=detail,
                issue_number=existing_number,
            )
            return {"outcome": "conflict", "issue_number": existing_number}

    body = (
        f"An upstream merge conflict occurred while syncing `{UPSTREAM_REPO}` into "
        f"`{FORK_REPO}` on branch `{branch}`.\n\n"
        "The service never auto-resolves conflicts. Resolve this manually:\n"
        "1. `git fetch upstream`\n"
        f"2. Merge `upstream/{branch}` into the fork's `{branch}` branch.\n"
        "3. Resolve the conflicts and commit the resolution.\n"
        "4. Open a pull request for review; do not push the resolution directly to the target branch."
    )
    issue = await deps.github.create_issue(
        title=f"Upstream sync conflict on {branch}",
        body=body,
        labels=[LABEL_NEEDS_HUMAN],
    )
    deps.db.set_meta("conflict_issue_number", str(issue.number))
    _record(
        deps,
        started_at,
        "conflict",
        before_sha=before_sha,
        issue_number=issue.number,
    )
    return {"outcome": "conflict", "issue_number": issue.number}


def _pull_request_body(commits, files: tuple[str, ...], branch: str) -> str:
    groups = grouped_commits(commits)
    counts = "\n".join(f"- {group}: {len(items)}" for group, items in groups.items())
    dependencies = [path for path in files if _REQUIREMENTS_FILE.fullmatch(path)]
    dependency_summary = (
        "\n".join(f"- `{path}`" for path in dependencies) if dependencies else "- None"
    )
    return (
        "Upstream changelog generated by `devin-superset-demo`.\n\n"
        f"Commit counts by group:\n{counts or '- No non-merge commits'}\n\n"
        f"Dependency files changed:\n{dependency_summary}\n\n"
        f"This changelog PR was opened by `devin-superset-demo`; it was never pushed directly to `{branch}`."
    )


async def run_upstream_sync(deps: Deps) -> dict:
    started_at = deps.clock()
    before_sha = None
    after_sha = None
    branch = deps.settings.upstream_sync_branch
    try:
        before_sha = await deps.github.get_branch_sha(branch)
        merge = await deps.github.merge_upstream(branch)
        if merge.outcome == "conflict":
            return await _record_conflict(deps, started_at, before_sha)
        if merge.outcome == "error":
            _record(
                deps,
                started_at,
                "error",
                before_sha=before_sha,
                detail="merge-upstream returned error",
            )
            return {"outcome": "error"}

        after_sha = await deps.github.get_branch_sha(branch)
        base_sha = deps.db.get_meta("changelog_through_sha") or before_sha
        if base_sha == after_sha:
            _record(
                deps,
                started_at,
                "none",
                before_sha=before_sha,
                after_sha=after_sha,
            )
            return {"outcome": "none"}

        comparison = await deps.github.compare(base_sha, after_sha)
        commits = included_commits(comparison.commits)
        if not commits:
            deps.db.set_meta("changelog_through_sha", after_sha)
            _record(
                deps,
                started_at,
                merge.outcome,
                before_sha=before_sha,
                after_sha=after_sha,
            )
            return {"outcome": merge.outcome}

        section = render_section(
            comparison.commits,
            comparison.files,
            base_sha,
            after_sha,
            datetime.fromtimestamp(started_at, UTC).date(),
        )
        existing = await deps.github.get_file("FORK_CHANGELOG.md", branch)
        content = prepend(existing, section)
        branch_name = f"devin/fork-changelog-{after_sha[:12]}"
        title = f"docs(fork-changelog): upstream sync {base_sha[:7]}..{after_sha[:7]}"
        body = _pull_request_body(commits, comparison.files, branch)
        pr_url = await deps.github.create_changelog_pr(
            base_branch=branch,
            head_sha=after_sha,
            branch_name=branch_name,
            content=content,
            title=title,
            body=body,
        )
        deps.db.set_meta("changelog_through_sha", after_sha)
        _record(
            deps,
            started_at,
            merge.outcome,
            before_sha=before_sha,
            after_sha=after_sha,
            pr_url=pr_url,
        )
        return {"outcome": merge.outcome, "pr_url": pr_url}
    except GitHubError as error:
        _record(
            deps,
            started_at,
            "error",
            before_sha=before_sha,
            after_sha=after_sha,
            detail=f"GitHub status {error.status_code}",
        )
        return {"outcome": "error", "error": "github_unavailable"}


def register(app: FastAPI, deps: Deps) -> None:
    async def upstream_sync_loop() -> None:
        while True:
            try:
                await run_upstream_sync(deps)
            except Exception:
                logger.exception("Unexpected upstream sync failure")
            await asyncio.sleep(deps.settings.upstream_sync_interval_s)

    if deps.settings.upstream_sync_enabled:
        deps.background.append(upstream_sync_loop)

    @app.post("/sync-upstream")
    async def sync_upstream(request: Request) -> JSONResponse:
        if not deps.settings.upstream_sync_enabled:
            return JSONResponse({"error": "upstream sync disabled"}, status_code=404)
        if not is_allowed_local_request(request, deps.settings.sweep_allowed_cidrs):
            return JSONResponse({"error": "forbidden"}, status_code=403)
        result = await run_upstream_sync(deps)
        return JSONResponse(result, status_code=502 if result.get("error") else 200)
