"""Scheduled upstream merges and changelog pull requests."""

from __future__ import annotations

import asyncio
import logging
import re
from datetime import UTC, datetime

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

from app.changelog import (
    DEPENDENCY_FILES_TRUNCATED_NOTE,
    grouped_commits,
    included_commits,
    prepend,
    render_section,
)
from app.github_client import GitHubError
from app.interfaces import Deps
from app.models import FORK_REPO, LABEL_NEEDS_HUMAN, UPSTREAM_REPO
from app.request_security import is_allowed_local_request

logger = logging.getLogger(__name__)
_REQUIREMENTS_FILE = re.compile(r"^requirements/[^/]+\.txt$")
_PENDING_BASE_SHA = "changelog_pending_base_sha"
_PENDING_OUTCOME = "changelog_pending_outcome"


def _normalize_message(message: str) -> str:
    return " ".join(message.split())[:300] or "no message"


def branch_meta_key(name: str, branch: str) -> str:
    return f"{name}:{branch}"


def _clear_pending_changelog(deps: Deps, branch: str) -> None:
    deps.db.delete_meta(branch_meta_key(_PENDING_BASE_SHA, branch))
    deps.db.delete_meta(branch_meta_key(_PENDING_OUTCOME, branch))


def _record(
    deps: Deps,
    started_at: float,
    outcome: str,
    *,
    before_sha: str | None = None,
    after_sha: str | None = None,
    detail: str | None = None,
    pr_url: str | None = None,
    issue_number: int | None = None,
) -> None:
    deps.db.record_upstream_sync(
        started_at,
        outcome,
        before_sha=before_sha,
        after_sha=after_sha,
        detail=detail,
        pr_url=pr_url,
        issue_number=issue_number,
    )


async def _record_conflict(
    deps: Deps,
    started_at: float,
    before_sha: str,
) -> dict:
    branch = deps.settings.upstream_sync_branch
    title = f"Upstream sync conflict on {branch}"
    conflict_key = branch_meta_key("conflict_issue_number", branch)
    stored_number = deps.db.get_meta(conflict_key)
    existing_number = int(stored_number) if stored_number and stored_number.isdecimal() else None
    existing_issue = None
    if existing_number is not None:
        try:
            existing_issue = await deps.github.get_issue(existing_number)
        except GitHubError as error:
            if error.status_code != 404:
                raise
    if existing_issue is None or existing_issue.state != "open" or existing_issue.is_pull_request:
        issues = await deps.github.list_open_issues_with_label(LABEL_NEEDS_HUMAN)
        existing_issue = next(
            (
                issue
                for issue in issues
                if issue.state == "open" and not issue.is_pull_request and issue.title == title
            ),
            None,
        )
    if existing_issue is not None:
        existing_number = existing_issue.number
        deps.db.set_meta(conflict_key, str(existing_number))
        detail = f"existing issue #{existing_number}"
        _record(
            deps,
            started_at,
            "conflict",
            before_sha=before_sha,
            detail=detail,
            issue_number=existing_number,
        )
        return {"outcome": "conflict", "issue_number": existing_number}

    body = (
        f"An upstream merge conflict occurred while syncing `{UPSTREAM_REPO}` into "
        f"`{FORK_REPO}` on branch `{branch}`.\n\n"
        "The service never auto-resolves conflicts. Resolve this manually:\n"
        "1. `git fetch upstream`\n"
        f"2. Merge `upstream/{branch}` into the fork's `{branch}` branch.\n"
        "3. Resolve the conflicts and commit the resolution.\n"
        "4. Open a pull request for review; do not push the resolution directly to the target branch."
    )
    issue = await deps.github.create_issue(
        title=title,
        body=body,
        labels=[LABEL_NEEDS_HUMAN],
    )
    deps.db.set_meta(conflict_key, str(issue.number))
    _record(
        deps,
        started_at,
        "conflict",
        before_sha=before_sha,
        issue_number=issue.number,
    )
    return {"outcome": "conflict", "issue_number": issue.number}


def _pull_request_body(
    commits,
    files: tuple[str, ...],
    branch: str,
    *,
    files_truncated: bool = False,
) -> str:
    groups = grouped_commits(commits)
    counts = "\n".join(f"- {group}: {len(items)}" for group, items in groups.items())
    dependencies = [path for path in files if _REQUIREMENTS_FILE.fullmatch(path)]
    dependency_summary = "\n".join(f"- `{path}`" for path in dependencies) if dependencies else "- None"
    if files_truncated:
        dependency_summary += f"\n\n{DEPENDENCY_FILES_TRUNCATED_NOTE}"
    return (
        "Upstream changelog generated by `devin-superset-demo`.\n\n"
        f"Commit counts by group:\n{counts or '- No non-merge commits'}\n\n"
        f"Dependency files changed:\n{dependency_summary}\n\n"
        f"This changelog PR was opened by `devin-superset-demo`; it was never pushed directly to `{branch}`."
    )


async def run_upstream_sync(deps: Deps) -> dict:
    started_at = deps.clock()
    before_sha = None
    after_sha = None
    base_sha = None
    branch = deps.settings.upstream_sync_branch
    through_key = branch_meta_key("changelog_through_sha", branch)
    pending_base_key = branch_meta_key(_PENDING_BASE_SHA, branch)
    pending_outcome_key = branch_meta_key(_PENDING_OUTCOME, branch)
    try:
        before_sha = await deps.github.get_branch_sha(branch)
        through_sha = deps.db.get_meta(through_key)
        pending_base_sha = deps.db.get_meta(pending_base_key)
        if pending_base_sha is None:
            pending_base_sha = through_sha or before_sha
            deps.db.set_meta(pending_base_key, pending_base_sha)

        merge = await deps.github.merge_upstream(branch)
        if merge.outcome == "conflict":
            return await _record_conflict(deps, started_at, before_sha)
        if merge.outcome == "error":
            msg = _normalize_message(merge.message)
            detail = f"merge-upstream returned error: {msg}"
            logger.warning("merge-upstream failed for %s: %s", branch, msg)
            _record(
                deps,
                started_at,
                "error",
                before_sha=before_sha,
                detail=detail,
            )
            return {"outcome": "error", "error": "merge_upstream_failed", "detail": msg}

        pending_outcome = deps.db.get_meta(pending_outcome_key)
        if merge.outcome in {"merged", "fast-forward"} or pending_outcome is None:
            pending_outcome = merge.outcome
            deps.db.set_meta(pending_outcome_key, pending_outcome)
        outcome = pending_outcome or merge.outcome

        after_sha = await deps.github.get_branch_sha(branch)
        base_sha = through_sha or pending_base_sha or before_sha
        if base_sha == after_sha:
            _clear_pending_changelog(deps, branch)
            _record(
                deps,
                started_at,
                "none",
                before_sha=before_sha,
                after_sha=after_sha,
            )
            return {"outcome": "none"}

        comparison = await deps.github.compare(base_sha, after_sha)
        commits = included_commits(comparison.commits)
        if not commits:
            deps.db.set_meta(through_key, after_sha)
            _clear_pending_changelog(deps, branch)
            _record(
                deps,
                started_at,
                outcome,
                before_sha=before_sha,
                after_sha=after_sha,
            )
            return {"outcome": outcome}

        section = render_section(
            comparison.commits,
            comparison.files,
            base_sha,
            after_sha,
            datetime.fromtimestamp(started_at, UTC).date(),
            files_truncated=comparison.files_truncated,
        )
        existing = await deps.github.get_file("FORK_CHANGELOG.md", branch)
        content = prepend(existing, section)
        branch_name = f"devin/fork-changelog-{after_sha[:12]}"
        title = f"docs(fork-changelog): upstream sync {base_sha[:7]}..{after_sha[:7]}"
        body = _pull_request_body(
            commits,
            comparison.files,
            branch,
            files_truncated=comparison.files_truncated,
        )
        pr_url = await deps.github.create_changelog_pr(
            base_branch=branch,
            head_sha=after_sha,
            branch_name=branch_name,
            content=content,
            title=title,
            body=body,
        )
        deps.db.set_meta(branch_meta_key("changelog_pr_url", branch), pr_url)
        deps.db.set_meta(through_key, after_sha)
        _clear_pending_changelog(deps, branch)
        _record(
            deps,
            started_at,
            outcome,
            before_sha=before_sha,
            after_sha=after_sha,
            pr_url=pr_url,
        )
        return {"outcome": outcome, "pr_url": pr_url}
    except GitHubError as error:
        msg = _normalize_message(error.message) if error.message.strip() else ""
        detail = f"GitHub status {error.status_code}: {msg}" if msg else f"GitHub status {error.status_code}"
        _record(
            deps,
            started_at,
            "error",
            before_sha=before_sha,
            after_sha=after_sha,
            detail=detail,
        )
        return {
            "outcome": "error",
            "error": "github_unavailable",
            "detail": msg or f"GitHub status {error.status_code}",
        }


def register(app: FastAPI, deps: Deps) -> None:
    run_lock = asyncio.Lock()

    async def upstream_sync_loop() -> None:
        while True:
            try:
                async with run_lock:
                    await run_upstream_sync(deps)
            except Exception:
                logger.exception("Unexpected upstream sync failure")
            await asyncio.sleep(deps.settings.upstream_sync_interval_s)

    if deps.settings.upstream_sync_enabled:
        deps.background.append(upstream_sync_loop)

    @app.post("/sync-upstream")
    async def sync_upstream(request: Request) -> JSONResponse:
        if not deps.settings.upstream_sync_enabled:
            return JSONResponse({"error": "upstream sync disabled"}, status_code=404)
        if not is_allowed_local_request(request, deps.settings.sweep_allowed_cidrs):
            return JSONResponse({"error": "forbidden"}, status_code=403)
        if run_lock.locked():
            return JSONResponse({"outcome": "busy"}, status_code=409)
        await run_lock.acquire()
        try:
            result = await run_upstream_sync(deps)
        finally:
            run_lock.release()
        return JSONResponse(result, status_code=502 if result.get("error") else 200)
