"""Send a signed demo GitHub webhook to the local service."""

import argparse
import hashlib
import hmac
import json
import os
import sys
import urllib.error
import urllib.request
import uuid
from pathlib import Path


def build_payload(
    issue: int,
    *,
    label: str = "devin:fixplease",
    repo: str = "dmonroym0/superset",
    seed_path: Path = Path(__file__).parents[1] / "app" / "demo" / "seed_issues.json",
) -> bytes:
    try:
        seed = json.loads(seed_path.read_text())
        seeded = next(item for item in seed["issues"] if item["number"] == issue)
    except (OSError, ValueError, KeyError, StopIteration):
        seeded = {
            "number": issue,
            "title": f"Synthetic demo issue #{issue}",
            "body": "Synthetic issue generated by the local webhook simulator.",
            "labels": [],
            "state": "open",
            "html_url": f"https://demo.invalid/{repo}/issues/{issue}",
        }
    payload = {
        "action": "labeled",
        "label": {"name": label, "color": "5319e7"},
        "issue": {
            "number": seeded["number"],
            "title": seeded["title"],
            "body": seeded.get("body") or "",
            "labels": [{"name": name} for name in seeded.get("labels", [])],
            "state": seeded.get("state", "open"),
            "html_url": seeded.get("html_url", ""),
            "user": {"login": "demo-user"},
        },
        "repository": {
            "full_name": repo,
            "name": repo.rsplit("/", 1)[-1],
            "owner": {"login": repo.split("/", 1)[0]},
        },
        "sender": {"login": "demo-user"},
    }
    return json.dumps(payload, separators=(",", ":")).encode()


def sign(secret: str, body: bytes) -> str:
    digest = hmac.new(secret.encode(), body, hashlib.sha256).hexdigest()
    return f"sha256={digest}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--issue", type=int, required=True)
    parser.add_argument("--url", default="http://127.0.0.1:8000/webhooks/github")
    parser.add_argument("--secret", default=os.environ.get("GITHUB_WEBHOOK_SECRET", "demo-only-not-a-secret"))
    parser.add_argument("--delivery-id")
    parser.add_argument("--bad-signature", action="store_true")
    parser.add_argument("--label", default="devin:fixplease")
    parser.add_argument("--repo", default="dmonroym0/superset")
    parser.add_argument("--event", default="issues")
    args = parser.parse_args(argv)

    body = build_payload(args.issue, label=args.label, repo=args.repo)
    signing_secret = "wrong-demo-only-not-a-secret" if args.bad_signature else args.secret
    headers = {
        "X-GitHub-Event": args.event,
        "X-GitHub-Delivery": args.delivery_id or str(uuid.uuid4()),
        "X-Hub-Signature-256": sign(signing_secret, body),
        "Content-Type": "application/json",
    }
    request = urllib.request.Request(args.url, data=body, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(request) as response:
            response_body = response.read().decode(errors="replace")
            print(f"HTTP {response.status} {response_body}")
            return 0 if 200 <= response.status < 300 else 1
    except urllib.error.HTTPError as error:
        response_body = error.read().decode(errors="replace")
        print(f"HTTP {error.code} {response_body}")
        return 0 if 200 <= error.code < 300 else 1
    except urllib.error.URLError:
        print("HTTP request failed")
        return 1


if __name__ == "__main__":
    sys.exit(main())
